### ISSUE TITLE
Quit the server with CTRL-BREAK. [12/Jun/2019 17:15:04] "POST /signup/doctor HTTP/1.1" 200 7330 [12/Jun/2019 17:15:09] "POST /signup/doctor HTTP/1.1" 200 7330 [12/Jun/2019 17:15:13] "GET /signup/doctor HTTP/1.1" 200 7082 [12/Jun/2019 17:15:15] "GET /signup/doctor HTTP/1.1" 200 7082 [12/Jun/2019 17:15:18] "GET /signup/doctor HTTP/1.1" 200 7082

### ISSUE THREAD

**Issue by asmat1** [apaar97/UpchaarWeb#4] opened 2019-06-12 12:27 UTC

**Comment by apaar97** [comment] 2019-06-17 13:07
No understandable issue title is mentioned. 
Please post the supporting stack trace, with the issue or error, separately.
Closing since the issue is unclear

**Closed by apaar97** 2019-06-17 13:07 UTC

**Comment by asmat1** [comment] 2019-06-30 11:36
Aoa

Sir doctor sign-up  ni ho raha

**Comment by apaar97** [comment] 2019-07-04 12:13
What error does it throw? You need to provide the corresponding error stack trace. It's difficult to debug without knowing the details.
